version: '3.8'

services:
  next-app-1:
    image: allower99/frontend-tu  # Используем готовый образ из Docker Hub
    ports:
      - "3000:3000"  # Пробрасываем порт 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  next-app-2:
    image: allower99/frontend-tu  # Используем готовый образ из Docker Hub
    ports:
      - "3000:3000"  # Пробрасываем порт 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  next-app-3:
    image: allower99/frontend-tu  # Используем готовый образ из Docker Hub
    ports:
      - "3000:3000"  # Пробрасываем порт 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - next-app
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt  # Для Let's Encrypt
      - ./data/certbot/www:/var/www/certbot
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
