version: '3.8'

services:
  next-app:
    image: allower99/frontend-tu:dev
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      replicas: 3   # создаём 3 контейнера фронтенда автоматически

  nginx:
    image: allower99/nginx-tu:latest
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/conf.d/allower.online.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

