version: '3.8'

services:
  next-app-1:
    image: allower99/frontend-tu  # Используем готовый образ из Docker Hub
    ports:
      - "3000:3000"  # Пробрасываем порт 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  next-app-2:
    image: allower99/frontend-tu  # Используем готовый образ из Docker Hub
    ports:
      - "3000:3000"  # Пробрасываем порт 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  next-app-3:
    image: allower99/frontend-tu  # Используем готовый образ из Docker Hub
    ports:
      - "3000:3000"  # Пробрасываем порт 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - next-app
    restart: unless-stopped
