version: '3.8'

services:
  next-app-1:
    build: .
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0  # Добавьте эту переменную
    networks:
      - app-network
    restart: unless-stopped

  next-app-2:
    build: .
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    networks:
      - app-network
    restart: unless-stopped

  next-app-3:
    build: .
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: allower99/nginx-tu
    networks:
      - app-network
    depends_on:
      - next-app-1
      - next-app-2
      - next-app-3
    volumes:
      - ./nginx/conf.d/allower.ru.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
