version: '3.8'

services:
  next-app-1:
    image: allower99/frontend-tu
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  next-app-2:
    image: allower99/frontend-tu
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  next-app-3:
    image: allower99/frontend-tu
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: allower99/nginx-tu
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/conf.d/allower.ru.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - next-app-1
      - next-app-2
      - next-app-3
    restart: unless-stopped
